<style>
	div#password {
		margin-top: 50px;
		display:block;
		width: 500px;
		height: 300px;
		margin: 0px auto;
		border: 2px solid black;
		padding-left: 10px;
	}
	
	form dl {		
		display: block;
		width: 300px;
		margin: 0px auto;
	}
	
	form dl dt {
		display: block;
		float: left;
		width: 100px;
	}
	
	form dl dt, form dl dd {
		display: block;
		heigth: 40px;
		line-height: 40px;	
	}


</style>
<div id="password">
	<p>
    	We have sent your new password. You can go to the <a href="<?php echo $this->url(array('controller'=>'index','action'=>'index'));?>">index</a>.
    </p>
	
  

    
</div>