<!DOCTYPE html>
<html>
<head>
	<?php 
	echo $this->jQuery()
	->setVersion('1.7.1')
	->setUiVersion('1.8.1')
	->addStylesheet('http://ajax.googleapis.com/ajax/libs/jqueryui/1.8.1/themes/smoothness/jquery-ui.css')	
	->enable()
	->uiEnable();
	?>
    <title>UserControl System</title> 
    <script>
    var users;
    
    window.onload = function(){ 
        if(document.editgroup.hidden.value != "") {   	
			users = document.editgroup.hidden.value.split(",");
        } else {
			users = new Array();
        } 
    	    	
  	  	var selectmenu=document.getElementById("users");
	    selectmenu.onchange=function() {
	    	var chosenoption=this.options[this.selectedIndex];
	    	
	    	if(chosenoption.value != 0) 
		    {	    			    		
	    		this.remove(this.selectedIndex);
	    		users.push(chosenoption.value);
	    		document.editgroup.hidden.value = users; 

	    		var tbl = document.getElementById('tblUsers');
	    		var lastRow = tbl.rows.length;	    		  
	    		var row = tbl.insertRow(lastRow); 
				row.id = 'row' + chosenoption.value;
					
	    		var cellLeft = row.insertCell(0);
	    		cellLeft.innerHTML = chosenoption.innerHTML;

	    		var cellRight = row.insertCell(1);	    		
	    		var link = document.createElement('a');
	    		link.setAttribute('onclick', 'removeUser(' + chosenoption.value + ',\'' + chosenoption.innerHTML + '\')');
	    		link.setAttribute('href', '#');	
	    		link.innerHTML = "Delete";
	    		cellRight.appendChild(link);
	    			 
	    	}
	    	    	
	    }	   
	    
    }

    function removeUser(id,mail) {        
        removeItem(users,id);
        document.editgroup.hidden.value = users;       
    	var row = document.getElementById('row'+id);
    	row.parentElement.removeChild(row); 
    	var select = document.getElementById("users");
    	select.options[select.options.length] = new Option(mail, id);    	
    	return false;
    }

    function removeItem(originalArray, itemToRemove) {
    	var j = 0;
    	while (j < originalArray.length) {
    	
	    	if (originalArray[j] == itemToRemove) {
	    	originalArray.splice(j, 1);
	    	} else {
	       		j++;
	       	}
    	}
    }  
    </script>   
    <style>
		body {
			Font-family: Calibri, Verdana, Ariel, sans-serif;	
		}
		
		ul li {
			list-style: none;	
		}
		
		ul li.ui-autocomplete {
			width: 200px;	
		}
		
		
		ul#menu {
			width: 600px;
			display: block;
			position: absolute;
		    top: 0px;
		    left: 50%;
			margin-left: -300px; 			
			background-color: gray;	
			float: right;	
			margin-top: 0px;		
		}
		
		ul#menu li {
			list-style: none;
			float: left;
			width: 100px;	
			background-color: gray;			
		}
		
		ul#menu li#logout {
			list-style: none;
			position: absolute;
			right: 0px;
			width: 100px;	
			background-color: gray;			
		}
		
		
		ul#menu li a {
			text-decoration: none;
			font-weight: bold;
			color: white;
		}
		
		div#content {
			margin-top: 40px;	
		}
		
	</style>
</head>
<body>
	<ul id="menu">
		<li><a href="<?php echo $this->url(array('controller'=>'user','action'=>'overview','page' => '1', 'search' =>null));?>">Overview</a></li>
		<li><a href="<?php echo $this->url(array('controller'=>'user','action'=>'add'));?>">Add user</a></li>
		<li><a href="<?php echo $this->url(array('controller'=>'group','action'=>'overview','page' => '1', 'search' =>null));?>">Groups</a></li>
		<li><a href="<?php echo $this->url(array('controller'=>'group','action'=>'add','page' => null, 'search' =>null));?>">Add group</a></li>
		<li id="logout"><a href="<?php echo $this->url(array('controller'=>'index','action'=>'logout'));?>">logout</a></li>
	</ul>
	<div id="content">
		<?php echo $this->layout()->content; ?>
	</div>
</body>
</html>
