<?php $this->headScript()->appendFile('/js/script.js','text/javascript');?>
<style>
	form dl {		
		display: block;
		width: 300px;
		margin: 0px auto;
	}
	
	form dl dt {
		display: block;
		float: left;
		width: 150px;
	}
	
	form dl dt, form dl dd {
		display: block;
		heigth: 40px;
		line-height: 40px;	
	}	
	
	p#errors {
		color: red;
		display: block;
		width: 100%;
		text-align: center;	
	}
	
	
	table {
		width: 600px;
		margin: 0 auto;	
	}
	
	th {
		text-align: left;	
	}
	
</style>
<div id="add">
	<p id="errors">
		<?php echo $this->error; ?>
	</p>
	<?php echo $this->form->render(); ?>
	<table id="tblUsers">
		<tr>
			<th>Email</th>					
			<th></th>
		</tr>
    <?php foreach ($this->users as $user): ?>
    	<tr id="row<?php echo $user->getId();?>">
		    <td><?php echo $this->escape($user->getEmail()); ?></td>      
		    
		    <td>		    	
				<a href="#" onclick="removeUser(<?php echo $user->getId() .',\''. $user->getEmail().'\'';?>)">Delete</a>
		    </td>
    	</tr>
    <?php endforeach ?>   
	</table>
</div>